name: Examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn add node-fetch
    - run: yarn build:lib
    - run: git submodule add --force https://github.com/trezor/trezor-common.git trezor-common
    - run: yarn pbjs -t json -p ./trezor-common/protob -o e2e/messages.json --keep-case messages-binance.proto messages-bitcoin.proto messages-bootloader.proto messages-cardano.proto messages-common.proto messages-crypto.proto messages-debug.proto messages-eos.proto messages-ethereum.proto messages-management.proto messages-monero.proto messages-nem.proto messages-ripple.proto messages-stellar.proto messages-tezos.proto messages-webauthn.proto messages.proto
    - run: ./e2e/run.sh -s "yarn example:bridge"
