name: Lint-ts-test-build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-ts-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn type-check
    - run: yarn lint
    - run: yarn test:unit
    - run: yarn build:lib
